[package]
name = "ddust1n/octree"
description = "A fork of Sleitnick's Octree from the NevermoreEngine."
license = "MIT"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
